params:
  HW_MSTATUS_FS_DIRTY_UPDATE: imprecise
  NAME: champsim
  LRSC_FAIL_ON_VA_SYNONYM: false
  LRSC_FAIL_ON_NON_EXACT_LRSC: false
  LRSC_MISALIGNED_BEHAVIOR: custom
  LRSC_RESERVATION_STRATEGY: custom
  MISALIGNED_AMO: false
  MSTATUS_FS_LEGAL_VALUES: [0, 3]
  MUTABLE_MISA_A: false
  MUTABLE_MISA_D: false
  MUTABLE_MISA_F: false
  MUTABLE_MISA_M: false
  XLEN: 64
